import { Book, Member, Borrowing } from './types';

export const initialBooks: Book[] = [
  {
    id: 'B-001',
    title: 'Laskar Pelangi',
    author: 'Andrea Hirata',
    publisher: 'Bentang Pustaka',
    category: 'Sastra & Novel',
    isbn: '978-979-3062-79-1',
    stock: 5,
    availableStock: 4,
    description: 'Kisah tentang perjuangan sepuluh anak di Belitung untuk mendapatkan pendidikan yang layak di sekolah dasar Muhammadiyah yang terancam ditutup.',
    coverColor: 'from-blue-500 to-indigo-600',
    createdAt: '2026-01-10',
  },
  {
    id: 'B-002',
    title: 'Bumi Manusia',
    author: 'Pramoedya Ananta Toer',
    publisher: 'Kepustakaan Populer Gramedia',
    category: 'Sastra & Novel',
    isbn: '978-979-97312-3-5',
    stock: 3,
    availableStock: 2,
    description: 'Novel sejarah berlatar belakang kebangkitan nasional pada masa kolonial Belanda, menceritakan tentang perjuangan cinta dan kesetaraan kelas antara Minke dan Annelies.',
    coverColor: 'from-slate-700 to-slate-900',
    createdAt: '2026-01-15',
  },
  {
    id: 'B-003',
    title: 'Filosofi Teras',
    author: 'Henry Manampiring',
    publisher: 'Kompas Gramedia',
    category: 'Pengembangan Diri',
    isbn: '978-602-06-2189-0',
    stock: 4,
    availableStock: 3,
    description: 'Sebuah buku pengantar filsafat Stoikisme atau Stoa yang disesuaikan secara praktis untuk mengatasi kecemasan dan kekhawatiran generasi muda saat ini.',
    coverColor: 'from-cyan-500 to-blue-600',
    createdAt: '2026-02-01',
  },
  {
    id: 'B-004',
    title: 'Rich Dad Poor Dad',
    author: 'Robert T. Kiyosaki',
    publisher: 'PT Gramedia Pustaka Utama',
    category: 'Bisnis & Keuangan',
    isbn: '978-602-03-3316-9',
    stock: 2,
    availableStock: 1,
    description: 'Membahas pemikiran finansial berbeda yang diajarkan oleh dua ayah, menuntun pembaca untuk mengerti aset, liabilitas, serta membangun kekayaan sejati.',
    coverColor: 'from-blue-800 to-indigo-900',
    createdAt: '2026-02-05',
  },
  {
    id: 'B-005',
    title: 'Sapiens: Sejarah Singkat Manusia',
    author: 'Yuval Noah Harari',
    publisher: 'Tangerang: Sastro',
    category: 'Sejarah & Budaya',
    isbn: '978-602-440-058-3',
    stock: 3,
    availableStock: 3,
    description: 'Menceritakan perkembangan kognitif, agrikultur, dan saintifik umat manusia dari zaman purba hingga masa depan modern yang penuh tantangan teknologi.',
    coverColor: 'from-amber-600 to-amber-950',
    createdAt: '2026-02-12',
  },
  {
    id: 'B-006',
    title: 'Sebuah Seni untuk Bersikap Bodo Amat',
    author: 'Mark Manson',
    publisher: 'PT Gramedia Pustaka Utama',
    category: 'Pengembangan Diri',
    isbn: '978-602-05-1125-2',
    stock: 6,
    availableStock: 5,
    description: 'Pendekatan waras untuk menjalani kehidupan yang bahagia, menyarankan pembaca untuk memilih masalah apa yang layak dipedulikan daripada menginginkan segala hal.',
    coverColor: 'from-orange-500 to-red-600',
    createdAt: '2026-02-20',
  },
  {
    id: 'B-007',
    title: 'Atomic Habits',
    author: 'James Clear',
    publisher: 'PT Gramedia Pustaka Utama',
    category: 'Pengembangan Diri',
    isbn: '978-602-06-3317-6',
    stock: 4,
    availableStock: 4,
    description: 'Menawarkan panduan praktis untuk membangun kebiasaan baik dan menghilangkan kebiasaan buruk melalui perubahan-perubahan kecil 1% setiap harinya.',
    coverColor: 'from-emerald-500 to-teal-700',
    createdAt: '2026-02-28',
  },
  {
    id: 'B-008',
    title: 'Pengantar Kecerdasan Buatan (AI)',
    author: 'Dr. Eng. Ir. Sunaryo',
    publisher: 'Informatika',
    category: 'Sains & Teknologi',
    isbn: '978-623-228-554-0',
    stock: 2,
    availableStock: 2,
    description: 'Pembahasan komprehensif mengenai konsep dasar kecerdasan buatan, jaringan saraf tiruan, pembelajaran mesin, dan implementasinya di era industri 4.0.',
    coverColor: 'from-blue-600 to-sky-500',
    createdAt: '2026-03-05',
  }
];

export const initialMembers: Member[] = [
  {
    id: 'M-001',
    name: 'Ahmad Fauzi',
    email: 'ahmad.fauzi@gmail.com',
    phone: '0812-3456-7890',
    joinDate: '2026-01-05',
    status: 'active',
  },
  {
    id: 'M-002',
    name: 'Siti Rahmawati',
    email: 'siti.rahma@yahoo.com',
    phone: '0813-9876-5432',
    joinDate: '2026-01-12',
    status: 'active',
  },
  {
    id: 'M-003',
    name: 'Budi Santoso',
    email: 'budi.santoso@outlook.com',
    phone: '0856-1122-3344',
    joinDate: '2026-02-10',
    status: 'active',
  },
  {
    id: 'M-004',
    name: 'Dewi Lestari',
    email: 'dewi.lestari@gmail.com',
    phone: '0821-4455-6677',
    joinDate: '2026-02-25',
    status: 'active',
  },
  {
    id: 'M-005',
    name: 'Rian Hidayat',
    email: 'rian.hidayat@gmail.com',
    phone: '0878-8899-0011',
    joinDate: '2026-03-01',
    status: 'inactive',
  }
];

export const initialBorrowings: Borrowing[] = [
  {
    id: 'T-001',
    bookId: 'B-001',
    memberId: 'M-001',
    borrowDate: '2026-07-10',
    dueDate: '2026-07-17',
    returnDate: null, // Overdue by 1 day (today is 2026-07-18)
    fine: 1000, // late return fine calculated
    status: 'overdue',
  },
  {
    id: 'T-002',
    bookId: 'B-002',
    memberId: 'M-002',
    borrowDate: '2026-07-12',
    dueDate: '2026-07-19',
    returnDate: null, // Still active and not overdue
    fine: 0,
    status: 'borrowed',
  },
  {
    id: 'T-003',
    bookId: 'B-003',
    memberId: 'M-003',
    borrowDate: '2026-07-14',
    dueDate: '2026-07-21',
    returnDate: null, // Still active
    fine: 0,
    status: 'borrowed',
  },
  {
    id: 'T-004',
    bookId: 'B-004',
    memberId: 'M-004',
    borrowDate: '2026-07-01',
    dueDate: '2026-07-08',
    returnDate: '2026-07-07', // Returned in time
    fine: 0,
    status: 'returned',
  },
  {
    id: 'T-005',
    bookId: 'B-006',
    memberId: 'M-001',
    borrowDate: '2026-07-15',
    dueDate: '2026-07-22',
    returnDate: null, // Still active
    fine: 0,
    status: 'borrowed',
  }
];
